name: Build release and upload to Nexus
on:
  push:
    branches:
      - ddl-989
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Build frontend and upload to Nexus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: |
          cd web
          npm i --legacy-peer-deps
          npm run build
        env:
          REACT_APP_API_BASE_URL: /dashboard
          CI: false

      - name: Upload to Nexus repository
        env:
          AUTH: ${{ secrets.NEXUS_CREDENTIALS }}
        run: |
          cd web/build
          zip -r appium-dashboard-frontend.zip *
          curl $AUTH -T appium-dashboard-frontend.zip "https://repository.smartdust.me/repository/appium/appium-dashboard-frontend.zip"
